export const NAIL_ART_ADD_ON = Object.freeze({
  id: 'nail-art-addon',
  title: 'Nail Art Add-on',
  pricePerNail: 49,
  description: 'Add custom designs, patterns, accents, or decorative details to selected nails.',
  note: 'Starting at ₱49 per nail. Final price may vary depending on design complexity, charms, gems, chrome, or other decorative details.',
});

export const SERVICES = [
  {
    id: 'gel-manicure',
    title: 'Gel Manicure',
    price: 299,
    icon: '✦',
    category: 'Signature',
    duration: '60–75 minutes',
    description: 'A clean, glossy gel manicure finished with careful shaping and long-lasting color.',
    included: ['Nail preparation and shaping', 'Gel color application', 'Finished cuticle care'],
    nailArtEligible: true,
  },
  {
    id: 'biab-structured-gel',
    title: 'BIAB / Structured Gel',
    price: 399,
    icon: '✧',
    category: 'Signature',
    duration: '75–90 minutes',
    description: 'Structured builder gel that adds strength while keeping the nails polished and natural-looking.',
    included: ['Nail preparation and shaping', 'Structured builder gel', 'Gel color finish'],
    nailArtEligible: true,
  },
  {
    id: 'soft-gel-extensions',
    title: 'Soft Gel Extensions',
    price: 499,
    icon: '◈',
    category: 'Signature',
    duration: '90–120 minutes',
    description: 'Lightweight full-cover extensions shaped and finished to suit your preferred style.',
    included: ['Nail preparation', 'Soft gel extension application', 'Shaping and gel color'],
    nailArtEligible: true,
  },
  {
    id: 'gel-removal',
    title: 'Gel Removal',
    price: 99,
    icon: '•',
    category: 'Other',
    duration: '20–30 minutes',
    description: 'Gentle removal of existing gel polish with care for the natural nail.',
    included: ['Safe product removal', 'Light nail clean-up'],
  },
  {
    id: 'biab-removal',
    title: 'BIAB Removal',
    price: 149,
    icon: '•',
    category: 'Other',
    duration: '30–45 minutes',
    description: 'Careful removal of builder gel or BIAB product from the natural nail.',
    included: ['Builder gel removal', 'Light nail clean-up'],
  },
  {
    id: 'soft-gel-extension-removal',
    title: 'Soft Gel Extension Removal',
    price: 199,
    icon: '•',
    category: 'Other',
    duration: '30–45 minutes',
    description: 'Safe removal of soft gel extensions while protecting the natural nail underneath.',
    included: ['Extension removal', 'Natural nail clean-up'],
  },
  {
    id: 'refill-for-extension',
    title: 'Refill for Extension',
    price: 299,
    icon: '•',
    category: 'Other',
    duration: '60–90 minutes',
    description: 'Refresh existing extensions by filling regrowth and restoring the shape and finish.',
    included: ['Regrowth refill', 'Reshaping', 'Gel color refresh'],
  },
  {
    id: 'repair',
    title: 'Repair',
    price: 49,
    icon: '•',
    category: 'Other',
    pricingUnit: 'nail',
    duration: '15–30 minutes',
    description: 'Repair a damaged or broken enhancement one nail at a time.',
    included: ['Damaged enhancement repair', 'Shape and finish restoration'],
    note: 'The final repair price is based on the number of nails selected.',
  },
];

export const formatPeso = (value) => `₱${Number(value).toLocaleString()}`;
